spring:
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'